# Generated by Django 4.2.23 on 2025-06-22 19:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("facturacion", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("contabilidad", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="asientocontable",
            name="documento_electronico",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="asientos_contables",
                to="facturacion.documentoelectronico",
                verbose_name="Documento Electrónico",
            ),
        ),
        migrations.AddField(
            model_name="asientocontable",
            name="ejercicio",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="asientos",
                to="contabilidad.ejerciciocontable",
                verbose_name="Ejercicio Contable",
            ),
        ),
        migrations.AddField(
            model_name="asientocontable",
            name="usuario_aprobacion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="asientos_aprobados",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuario Aprobación",
            ),
        ),
        migrations.AddField(
            model_name="asientocontable",
            name="usuario_creacion",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="asientos_creados",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuario Creación",
            ),
        ),
        migrations.AddIndex(
            model_name="plancuentas",
            index=models.Index(fields=["codigo"], name="idx_plan_codigo"),
        ),
        migrations.AddIndex(
            model_name="plancuentas",
            index=models.Index(fields=["elemento_pcge"], name="idx_plan_elemento"),
        ),
        migrations.AddIndex(
            model_name="plancuentas",
            index=models.Index(fields=["tipo_cuenta"], name="idx_plan_tipo"),
        ),
        migrations.AddIndex(
            model_name="plancuentas",
            index=models.Index(fields=["naturaleza"], name="idx_plan_naturaleza"),
        ),
        migrations.AddIndex(
            model_name="plancuentas",
            index=models.Index(fields=["cuenta_padre"], name="idx_plan_padre"),
        ),
        migrations.AddIndex(
            model_name="plancuentas",
            index=models.Index(
                fields=["acepta_movimientos"], name="idx_plan_movimientos"
            ),
        ),
        migrations.AddIndex(
            model_name="plancuentas",
            index=models.Index(fields=["uso_automatico"], name="idx_plan_automatico"),
        ),
        migrations.AddIndex(
            model_name="plancuentas",
            index=models.Index(fields=["activo"], name="idx_plan_activo"),
        ),
        migrations.AddIndex(
            model_name="ejerciciocontable",
            index=models.Index(fields=["codigo"], name="idx_ejercicio_codigo"),
        ),
        migrations.AddIndex(
            model_name="ejerciciocontable",
            index=models.Index(fields=["fecha_inicio"], name="idx_ejercicio_inicio"),
        ),
        migrations.AddIndex(
            model_name="ejerciciocontable",
            index=models.Index(fields=["fecha_fin"], name="idx_ejercicio_fin"),
        ),
        migrations.AddIndex(
            model_name="ejerciciocontable",
            index=models.Index(fields=["estado"], name="idx_ejercicio_estado"),
        ),
        migrations.AddIndex(
            model_name="ejerciciocontable",
            index=models.Index(fields=["es_actual"], name="idx_ejercicio_actual"),
        ),
        migrations.AddIndex(
            model_name="ejerciciocontable",
            index=models.Index(fields=["activo"], name="idx_ejercicio_activo"),
        ),
        migrations.AddIndex(
            model_name="detalleasiento",
            index=models.Index(fields=["asiento"], name="idx_detal_asient_contable"),
        ),
        migrations.AddIndex(
            model_name="detalleasiento",
            index=models.Index(fields=["cuenta"], name="idx_detal_asient_cuenta"),
        ),
        migrations.AddIndex(
            model_name="detalleasiento",
            index=models.Index(fields=["numero_linea"], name="idx_detal_asien_linea"),
        ),
        migrations.AddIndex(
            model_name="detalleasiento",
            index=models.Index(fields=["debe"], name="idx_detal_debe"),
        ),
        migrations.AddIndex(
            model_name="detalleasiento",
            index=models.Index(fields=["haber"], name="idx_detal_haber"),
        ),
        migrations.AddIndex(
            model_name="detalleasiento",
            index=models.Index(fields=["cliente_proveedor"], name="idx_detal_tercero"),
        ),
        migrations.AddIndex(
            model_name="detalleasiento",
            index=models.Index(
                fields=["activo"], name="idx_detal_asient_contab_activo"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="detalleasiento",
            unique_together={("asiento", "numero_linea")},
        ),
        migrations.AddIndex(
            model_name="asientocontable",
            index=models.Index(fields=["numero"], name="idx_asiento_numero"),
        ),
        migrations.AddIndex(
            model_name="asientocontable",
            index=models.Index(fields=["fecha"], name="idx_asiento_fecha"),
        ),
        migrations.AddIndex(
            model_name="asientocontable",
            index=models.Index(fields=["tipo_asiento"], name="idx_asiento_tipo"),
        ),
        migrations.AddIndex(
            model_name="asientocontable",
            index=models.Index(fields=["estado"], name="idx_asiento_estado"),
        ),
        migrations.AddIndex(
            model_name="asientocontable",
            index=models.Index(fields=["ejercicio"], name="idx_asiento_ejercicio"),
        ),
        migrations.AddIndex(
            model_name="asientocontable",
            index=models.Index(fields=["usuario_creacion"], name="idx_asiento_usuario"),
        ),
        migrations.AddIndex(
            model_name="asientocontable",
            index=models.Index(
                fields=["documento_electronico"], name="idx_asiento_documento"
            ),
        ),
        migrations.AddIndex(
            model_name="asientocontable",
            index=models.Index(fields=["es_automatico"], name="idx_asiento_automatico"),
        ),
        migrations.AddIndex(
            model_name="asientocontable",
            index=models.Index(fields=["activo"], name="idx_asiento_activo"),
        ),
        migrations.AlterUniqueTogether(
            name="asientocontable",
            unique_together={("ejercicio", "numero")},
        ),
    ]
