# Generated by Django 4.2.23 on 2025-06-25 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="configuracionsistema",
            new_name="idx_core_config_clave",
            old_name="idx_config_clave",
        ),
        migrations.RenameIndex(
            model_name="configuracionsistema",
            new_name="idx_core_config_activo",
            old_name="idx_config_activo",
        ),
    ]
