# Generated by Django 4.2.23 on 2025-06-19 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario",
            name="empresa",
            field=models.ForeignKey(
                blank=True,
                help_text="Empresa a la que pertenece el usuario",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="usuarios",
                to="core.empresa",
                verbose_name="Empresa",
            ),
        ),
    ]
