# Generated by Django 4.2.23 on 2025-06-21 15:50

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0002_alter_usuario_empresa"),
    ]

    operations = [
        migrations.CreateModel(
            name="PerfilUsuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Fecha y hora de creación del registro",
                        verbose_name="Fecha de Creación",
                    ),
                ),
                (
                    "fecha_actualizacion",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Fecha y hora de última actualización",
                        verbose_name="Fecha de Actualización",
                    ),
                ),
                (
                    "activo",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Indica si el registro está activo",
                        verbose_name="Activo",
                    ),
                ),
                (
                    "fecha_nacimiento",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de Nacimiento"
                    ),
                ),
                ("direccion", models.TextField(blank=True, verbose_name="Dirección")),
                (
                    "ciudad",
                    models.CharField(blank=True, max_length=100, verbose_name="Ciudad"),
                ),
                (
                    "pais",
                    models.CharField(
                        default="Perú", max_length=50, verbose_name="País"
                    ),
                ),
                (
                    "tema_oscuro",
                    models.BooleanField(default=False, verbose_name="Tema Oscuro"),
                ),
                (
                    "idioma",
                    models.CharField(
                        choices=[("es", "Español"), ("en", "English")],
                        default="es",
                        max_length=10,
                        verbose_name="Idioma",
                    ),
                ),
                (
                    "timezone",
                    models.CharField(
                        default="America/Lima",
                        max_length=50,
                        verbose_name="Zona Horaria",
                    ),
                ),
                (
                    "configuracion_dashboard",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Configuración personalizada del dashboard",
                        verbose_name="Configuración Dashboard",
                    ),
                ),
                (
                    "cargo",
                    models.CharField(blank=True, max_length=100, verbose_name="Cargo"),
                ),
                (
                    "empresa",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Empresa"
                    ),
                ),
                ("biografia", models.TextField(blank=True, verbose_name="Biografía")),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="usuarios/avatars/",
                        verbose_name="Avatar",
                    ),
                ),
            ],
            options={
                "verbose_name": "Perfil de Usuario",
                "verbose_name_plural": "Perfiles de Usuario",
                "db_table": "usuarios_perfil",
            },
        ),
        migrations.CreateModel(
            name="Rol",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Fecha y hora de creación del registro",
                        verbose_name="Fecha de Creación",
                    ),
                ),
                (
                    "fecha_actualizacion",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Fecha y hora de última actualización",
                        verbose_name="Fecha de Actualización",
                    ),
                ),
                (
                    "activo",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Indica si el registro está activo",
                        verbose_name="Activo",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        help_text="Nombre único del rol en el sistema",
                        max_length=50,
                        unique=True,
                        verbose_name="Nombre del Rol",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        choices=[
                            ("administrador", "Administrador"),
                            ("contador", "Contador"),
                            ("vendedor", "Vendedor"),
                            ("cliente", "Cliente"),
                        ],
                        help_text="Código interno del rol",
                        max_length=20,
                        unique=True,
                        verbose_name="Código del Rol",
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(
                        help_text="Descripción detallada del rol y sus permisos",
                        verbose_name="Descripción",
                    ),
                ),
                (
                    "nivel_acceso",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Nivel numérico de acceso (mayor número = más permisos)",
                        verbose_name="Nivel de Acceso",
                    ),
                ),
                (
                    "permisos_especiales",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Configuración JSON de permisos específicos",
                        verbose_name="Permisos Especiales",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rol",
                "verbose_name_plural": "Roles",
                "db_table": "usuarios_rol",
                "ordering": ["nivel_acceso", "nombre"],
            },
        ),
        migrations.AlterUniqueTogether(
            name="usuariosucursal",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="usuariosucursal",
            name="asignado_por",
        ),
        migrations.RemoveField(
            model_name="usuariosucursal",
            name="sucursal",
        ),
        migrations.RemoveField(
            model_name="usuariosucursal",
            name="usuario",
        ),
        migrations.AlterModelOptions(
            name="sesionusuario",
            options={
                "ordering": ["-fecha_ultimo_uso"],
                "verbose_name": "Sesión de Usuario",
                "verbose_name_plural": "Sesiones de Usuario",
            },
        ),
        migrations.AlterModelOptions(
            name="usuario",
            options={
                "ordering": ["nombres", "apellidos"],
                "verbose_name": "Usuario",
                "verbose_name_plural": "Usuarios",
            },
        ),
        migrations.AlterModelManagers(
            name="usuario",
            managers=[],
        ),
        migrations.RemoveIndex(
            model_name="sesionusuario",
            name="idx_sesion_usuario_activa",
        ),
        migrations.RemoveIndex(
            model_name="sesionusuario",
            name="idx_sesion_key",
        ),
        migrations.RemoveIndex(
            model_name="sesionusuario",
            name="idx_sesion_inicio",
        ),
        migrations.RemoveIndex(
            model_name="usuario",
            name="idx_usuario_dni",
        ),
        migrations.RemoveIndex(
            model_name="usuario",
            name="idx_usuario_empresa",
        ),
        migrations.RemoveIndex(
            model_name="usuario",
            name="idx_usuario_actividad",
        ),
        migrations.RemoveIndex(
            model_name="usuario",
            name="idx_usuario_bloqueado",
        ),
        migrations.RemoveField(
            model_name="sesionusuario",
            name="fecha_fin",
        ),
        migrations.RemoveField(
            model_name="sesionusuario",
            name="session_key",
        ),
        migrations.RemoveField(
            model_name="usuario",
            name="avatar",
        ),
        migrations.RemoveField(
            model_name="usuario",
            name="cargo",
        ),
        migrations.RemoveField(
            model_name="usuario",
            name="creado_por",
        ),
        migrations.RemoveField(
            model_name="usuario",
            name="cuenta_bloqueada_hasta",
        ),
        migrations.RemoveField(
            model_name="usuario",
            name="date_joined",
        ),
        migrations.RemoveField(
            model_name="usuario",
            name="direccion",
        ),
        migrations.RemoveField(
            model_name="usuario",
            name="dni",
        ),
        migrations.RemoveField(
            model_name="usuario",
            name="empresa",
        ),
        migrations.RemoveField(
            model_name="usuario",
            name="fecha_nacimiento",
        ),
        migrations.RemoveField(
            model_name="usuario",
            name="fecha_ultimo_login_fallido",
        ),
        migrations.RemoveField(
            model_name="usuario",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="usuario",
            name="idioma",
        ),
        migrations.RemoveField(
            model_name="usuario",
            name="last_name",
        ),
        migrations.RemoveField(
            model_name="usuario",
            name="notificar_email",
        ),
        migrations.RemoveField(
            model_name="usuario",
            name="notificar_facturas",
        ),
        migrations.RemoveField(
            model_name="usuario",
            name="notificar_reportes",
        ),
        migrations.RemoveField(
            model_name="usuario",
            name="requiere_cambio_password",
        ),
        migrations.RemoveField(
            model_name="usuario",
            name="sucursales",
        ),
        migrations.RemoveField(
            model_name="usuario",
            name="telefono_emergencia",
        ),
        migrations.RemoveField(
            model_name="usuario",
            name="tema_interfaz",
        ),
        migrations.RemoveField(
            model_name="usuario",
            name="ultima_actividad",
        ),
        migrations.RemoveField(
            model_name="usuario",
            name="username",
        ),
        migrations.RemoveField(
            model_name="usuario",
            name="zona_horaria",
        ),
        migrations.AddField(
            model_name="sesionusuario",
            name="activo",
            field=models.BooleanField(
                db_index=True,
                default=True,
                help_text="Indica si el registro está activo",
                verbose_name="Activo",
            ),
        ),
        migrations.AddField(
            model_name="sesionusuario",
            name="fecha_actualizacion",
            field=models.DateTimeField(
                auto_now=True,
                db_index=True,
                help_text="Fecha y hora de última actualización",
                verbose_name="Fecha de Actualización",
            ),
        ),
        migrations.AddField(
            model_name="sesionusuario",
            name="fecha_creacion",
            field=models.DateTimeField(
                auto_now_add=True,
                db_index=True,
                default="2025-06-21 00:00:00",
                help_text="Fecha y hora de creación del registro",
                verbose_name="Fecha de Creación",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="sesionusuario",
            name="fecha_expiracion",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 7, 21, 15, 46, 28, 830179, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Fecha de Expiración",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="sesionusuario",
            name="fecha_ultimo_uso",
            field=models.DateTimeField(auto_now=True, verbose_name="Último Uso"),
        ),
        migrations.AddField(
            model_name="sesionusuario",
            name="token_sesion",
            field=models.CharField(
                default="temp_token_1750520931",
                max_length=255,
                unique=True,
                verbose_name="Token de Sesión",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="usuario",
            name="apellidos",
            field=models.CharField(
                default="Apellido",
                help_text="Apellidos completos del usuario",
                max_length=100,
                verbose_name="Apellidos",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="usuario",
            name="debe_cambiar_password",
            field=models.BooleanField(
                default=False, verbose_name="Debe Cambiar Contraseña"
            ),
        ),
        migrations.AddField(
            model_name="usuario",
            name="estado_usuario",
            field=models.CharField(
                choices=[
                    ("activo", "Activo"),
                    ("inactivo", "Inactivo"),
                    ("suspendido", "Suspendido"),
                    ("bloqueado", "Bloqueado"),
                ],
                default="activo",
                max_length=20,
                verbose_name="Estado del Usuario",
            ),
        ),
        migrations.AddField(
            model_name="usuario",
            name="fecha_bloqueo",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Fecha de Bloqueo"
            ),
        ),
        migrations.AddField(
            model_name="usuario",
            name="fecha_cambio_password",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Última Cambio de Contraseña"
            ),
        ),
        migrations.AddField(
            model_name="usuario",
            name="fecha_ultimo_login",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Último Login"
            ),
        ),
        migrations.AddField(
            model_name="usuario",
            name="nombres",
            field=models.CharField(
                default="Nombre",
                help_text="Nombres completos del usuario",
                max_length=100,
                verbose_name="Nombres",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="usuario",
            name="notificaciones_email",
            field=models.BooleanField(
                default=True, verbose_name="Recibir Notificaciones por Email"
            ),
        ),
        migrations.AddField(
            model_name="usuario",
            name="notificaciones_sistema",
            field=models.BooleanField(
                default=True, verbose_name="Mostrar Notificaciones en Sistema"
            ),
        ),
        migrations.AddField(
            model_name="usuario",
            name="numero_documento",
            field=models.CharField(
                default="00000000",
                max_length=20,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Formato de documento inválido",
                        regex="^[0-9A-Z]{8,20}$",
                    )
                ],
                verbose_name="Número de Documento",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="usuario",
            name="tipo_documento",
            field=models.CharField(
                choices=[
                    ("dni", "DNI"),
                    ("ruc", "RUC"),
                    ("carnet_extranjeria", "Carnet de Extranjería"),
                    ("pasaporte", "Pasaporte"),
                ],
                default="dni",
                max_length=20,
                verbose_name="Tipo de Documento",
            ),
        ),
        migrations.AlterField(
            model_name="sesionusuario",
            name="activa",
            field=models.BooleanField(default=True, verbose_name="Sesión Activa"),
        ),
        migrations.AlterField(
            model_name="sesionusuario",
            name="fecha_inicio",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Fecha de Inicio"
            ),
        ),
        migrations.AlterField(
            model_name="sesionusuario",
            name="ip_address",
            field=models.GenericIPAddressField(verbose_name="Dirección IP"),
        ),
        migrations.AlterField(
            model_name="sesionusuario",
            name="user_agent",
            field=models.TextField(verbose_name="User Agent"),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="email",
            field=models.EmailField(
                help_text="Email único para login",
                max_length=254,
                unique=True,
                validators=[django.core.validators.EmailValidator()],
                verbose_name="Email",
            ),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="intentos_login_fallidos",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Intentos de Login Fallidos"
            ),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Usuario puede hacer login",
                verbose_name="Usuario Activo",
            ),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="is_staff",
            field=models.BooleanField(
                default=False,
                help_text="Puede acceder al panel de administración",
                verbose_name="Es Staff",
            ),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="telefono",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Formato de teléfono inválido",
                        regex="^\\+?[0-9\\s\\-\\(\\)]{7,20}$",
                    )
                ],
                verbose_name="Teléfono",
            ),
        ),
        migrations.AddIndex(
            model_name="sesionusuario",
            index=models.Index(fields=["usuario"], name="idx_sesion_usuario"),
        ),
        migrations.AddIndex(
            model_name="sesionusuario",
            index=models.Index(fields=["token_sesion"], name="idx_sesion_token"),
        ),
        migrations.AddIndex(
            model_name="sesionusuario",
            index=models.Index(fields=["activa"], name="idx_sesion_activa"),
        ),
        migrations.AddIndex(
            model_name="sesionusuario",
            index=models.Index(
                fields=["fecha_expiracion"], name="idx_sesion_expiracion"
            ),
        ),
        migrations.AddIndex(
            model_name="usuario",
            index=models.Index(
                fields=["numero_documento"], name="idx_usuario_documento"
            ),
        ),
        migrations.AddIndex(
            model_name="usuario",
            index=models.Index(fields=["estado_usuario"], name="idx_usuario_estado"),
        ),
        migrations.AddIndex(
            model_name="usuario",
            index=models.Index(fields=["rol"], name="idx_usuario_rol"),
        ),
        migrations.AlterModelTable(
            name="sesionusuario",
            table="usuarios_sesion",
        ),
        migrations.DeleteModel(
            name="UsuarioSucursal",
        ),
        migrations.AddIndex(
            model_name="rol",
            index=models.Index(fields=["codigo"], name="idx_rol_codigo"),
        ),
        migrations.AddIndex(
            model_name="rol",
            index=models.Index(fields=["nivel_acceso"], name="idx_rol_nivel"),
        ),
        migrations.AddField(
            model_name="perfilusuario",
            name="usuario",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="perfil",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuario",
            ),
        ),
        migrations.AddField(
            model_name="usuario",
            name="rol",
            field=models.ForeignKey(
                default=1,
                help_text="Rol asignado que define permisos",
                on_delete=django.db.models.deletion.PROTECT,
                to="usuarios.rol",
                verbose_name="Rol del Usuario",
            ),
            preserve_default=False,
        ),
    ]
